export const ListSeat = [
    {
        maGhe: 49961,
        tenGhe: 'A1',
        loaiGhe: 'NORMAL',
        stt: '01',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49962,
        tenGhe: 'A2',
        loaiGhe: 'NORMAL',
        stt: '02',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49963,
        tenGhe: 'A3',
        loaiGhe: 'NORMAL',
        stt: '03',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49964,
        tenGhe: 'A4',
        loaiGhe: 'NORMAL',
        stt: '04',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49965,
        tenGhe: 'A5',
        loaiGhe: 'NORMAL',
        stt: '05',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49966,
        tenGhe: 'A6',
        loaiGhe: 'NORMAL',
        stt: '06',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49967,
        tenGhe: 'A7',
        loaiGhe: 'NORMAL',
        stt: '07',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49968,
        tenGhe: 'A8',
        loaiGhe: 'NORMAL',
        stt: '08',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49969,
        tenGhe: 'A9',
        loaiGhe: 'NORMAL',
        stt: '09',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49970,
        tenGhe: 'A10',
        loaiGhe: 'NORMAL',
        stt: '10',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49971,
        tenGhe: 'A11',
        loaiGhe: 'NORMAL',
        stt: '11',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49972,
        tenGhe: 'A12',
        loaiGhe: 'NORMAL',
        stt: '12',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49973,
        tenGhe: 'B1',
        loaiGhe: 'NORMAL',
        stt: '13',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49974,
        tenGhe: 'B2',
        loaiGhe: 'NORMAL',
        stt: '14',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49975,
        tenGhe: 'B3',
        loaiGhe: 'NORMAL',
        stt: '15',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49976,
        tenGhe: 'B4',
        loaiGhe: 'NORMAL',
        stt: '16',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49977,
        tenGhe: 'B5',
        loaiGhe: 'NORMAL',
        stt: '17',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49978,
        tenGhe: 'B6',
        loaiGhe: 'NORMAL',
        stt: '18',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49979,
        tenGhe: 'B7',
        loaiGhe: 'NORMAL',
        stt: '19',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49980,
        tenGhe: 'B8',
        loaiGhe: 'NORMAL',
        stt: '20',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49981,
        tenGhe: 'B9',
        loaiGhe: 'NORMAL',
        stt: '21',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49982,
        tenGhe: 'B10',
        loaiGhe: 'NORMAL',
        stt: '22',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49983,
        tenGhe: 'B11',
        loaiGhe: 'NORMAL',
        stt: '23',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49984,
        tenGhe: 'B12',
        loaiGhe: 'NORMAL',
        stt: '24',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49985,
        tenGhe: 'C1',
        loaiGhe: 'NORMAL',
        stt: '25',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49986,
        tenGhe: 'C2',
        loaiGhe: 'NORMAL',
        stt: '26',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49987,
        tenGhe: 'C3',
        loaiGhe: 'NORMAL',
        stt: '27',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49988,
        tenGhe: 'C4',
        loaiGhe: 'NORMAL',
        stt: '28',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49989,
        tenGhe: 'C5',
        loaiGhe: 'NORMAL',
        stt: '29',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49990,
        tenGhe: 'C6',
        loaiGhe: 'NORMAL',
        stt: '30',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49991,
        tenGhe: 'C7',
        loaiGhe: 'NORMAL',
        stt: '31',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49992,
        tenGhe: 'C8',
        loaiGhe: 'NORMAL',
        stt: '32',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49993,
        tenGhe: 'C9',
        loaiGhe: 'NORMAL',
        stt: '33',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49994,
        tenGhe: 'C10',
        loaiGhe: 'NORMAL',
        stt: '34',
        giaVe: 75000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49995,
        tenGhe: 'C11',
        loaiGhe: 'NORMAL',
        stt: '35',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49996,
        tenGhe: 'C12',
        loaiGhe: 'NORMAL',
        stt: '36',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49997,
        tenGhe: 'D1',
        loaiGhe: 'VIP',
        stt: '37',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49998,
        tenGhe: 'D2',
        loaiGhe: 'VIP',
        stt: '38',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 49999,
        tenGhe: 'D3',
        loaiGhe: 'VIP',
        stt: '39',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50000,
        tenGhe: 'D4',
        loaiGhe: 'VIP',
        stt: '40',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50001,
        tenGhe: 'D5',
        loaiGhe: 'VIP',
        stt: '41',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50002,
        tenGhe: 'D6',
        loaiGhe: 'VIP',
        stt: '42',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50003,
        tenGhe: 'D7',
        loaiGhe: 'VIP',
        stt: '43',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50004,
        tenGhe: 'D8',
        loaiGhe: 'VIP',
        stt: '44',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50005,
        tenGhe: 'D9',
        loaiGhe: 'VIP',
        stt: '45',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50006,
        tenGhe: 'D10',
        loaiGhe: 'VIP',
        stt: '46',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50007,
        tenGhe: 'D11',
        loaiGhe: 'VIP',
        stt: '47',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50008,
        tenGhe: 'D12',
        loaiGhe: 'VIP',
        stt: '48',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50009,
        tenGhe: 'E1',
        loaiGhe: 'VIP',
        stt: '49',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50010,
        tenGhe: 'E2',
        loaiGhe: 'VIP',
        stt: '50',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50011,
        tenGhe: 'E3',
        loaiGhe: 'VIP',
        stt: '51',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50012,
        tenGhe: 'E4',
        loaiGhe: 'VIP',
        stt: '52',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50013,
        tenGhe: 'E5',
        loaiGhe: 'VIP',
        stt: '53',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50014,
        tenGhe: 'E6',
        loaiGhe: 'VIP',
        stt: '54',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50015,
        tenGhe: 'E7',
        loaiGhe: 'VIP',
        stt: '55',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50016,
        tenGhe: 'E8',
        loaiGhe: 'VIP',
        stt: '56',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50017,
        tenGhe: 'E9',
        loaiGhe: 'VIP',
        stt: '57',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50018,
        tenGhe: 'E10',
        loaiGhe: 'VIP',
        stt: '58',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50019,
        tenGhe: 'E11',
        loaiGhe: 'VIP',
        stt: '59',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50020,
        tenGhe: 'E12',
        loaiGhe: 'VIP',
        stt: '60',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50021,
        tenGhe: 'F1',
        loaiGhe: 'VIP',
        stt: '61',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50022,
        tenGhe: 'F2',
        loaiGhe: 'VIP',
        stt: '62',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50023,
        tenGhe: 'F3',
        loaiGhe: 'VIP',
        stt: '63',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50024,
        tenGhe: 'F4',
        loaiGhe: 'VIP',
        stt: '64',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50025,
        tenGhe: 'F5',
        loaiGhe: 'VIP',
        stt: '65',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50026,
        tenGhe: 'F6',
        loaiGhe: 'VIP',
        stt: '66',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50027,
        tenGhe: 'F7',
        loaiGhe: 'VIP',
        stt: '67',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50028,
        tenGhe: 'F8',
        loaiGhe: 'VIP',
        stt: '68',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50029,
        tenGhe: 'F9',
        loaiGhe: 'VIP',
        stt: '69',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50030,
        tenGhe: 'F10',
        loaiGhe: 'VIP',
        stt: '70',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50031,
        tenGhe: 'F11',
        loaiGhe: 'VIP',
        stt: '71',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50032,
        tenGhe: 'F12',
        loaiGhe: 'VIP',
        stt: '72',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50033,
        tenGhe: 'G1',
        loaiGhe: 'VIP',
        stt: '73',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50034,
        tenGhe: 'G2',
        loaiGhe: 'VIP',
        stt: '74',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50035,
        tenGhe: 'G3',
        loaiGhe: 'VIP',
        stt: '75',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50036,
        tenGhe: 'G4',
        loaiGhe: 'VIP',
        stt: '76',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50037,
        tenGhe: 'G5',
        loaiGhe: 'VIP',
        stt: '77',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50038,
        tenGhe: 'G6',
        loaiGhe: 'VIP',
        stt: '78',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50039,
        tenGhe: 'G7',
        loaiGhe: 'VIP',
        stt: '79',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50040,
        tenGhe: 'G8',
        loaiGhe: 'VIP',
        stt: '80',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50041,
        tenGhe: 'G9',
        loaiGhe: 'VIP',
        stt: '81',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50042,
        tenGhe: 'G10',
        loaiGhe: 'VIP',
        stt: '82',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50043,
        tenGhe: 'G11',
        loaiGhe: 'VIP',
        stt: '83',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50044,
        tenGhe: 'G12',
        loaiGhe: 'VIP',
        stt: '84',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50045,
        tenGhe: 'H1',
        loaiGhe: 'VIP',
        stt: '85',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50046,
        tenGhe: 'H2',
        loaiGhe: 'VIP',
        stt: '86',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50047,
        tenGhe: 'H3',
        loaiGhe: 'VIP',
        stt: '87',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50048,
        tenGhe: 'H4',
        loaiGhe: 'VIP',
        stt: '88',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50049,
        tenGhe: 'H5',
        loaiGhe: 'VIP',
        stt: '89',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50050,
        tenGhe: 'H6',
        loaiGhe: 'VIP',
        stt: '90',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50051,
        tenGhe: 'H7',
        loaiGhe: 'VIP',
        stt: '91',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50052,
        tenGhe: 'H8',
        loaiGhe: 'VIP',
        stt: '92',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50053,
        tenGhe: 'H9',
        loaiGhe: 'VIP',
        stt: '93',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50054,
        tenGhe: 'H10',
        loaiGhe: 'VIP',
        stt: '94',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50055,
        tenGhe: 'H11',
        loaiGhe: 'VIP',
        stt: '95',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50056,
        tenGhe: 'H12',
        loaiGhe: 'VIP',
        stt: '96',
        giaVe: 80000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50057,
        tenGhe: 'I1-I2',
        loaiGhe: 'TWIN',
        stt: '97',
        giaVe: 170000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50058,
        tenGhe: 'I3-I4',
        loaiGhe: 'TWIN',
        stt: '98',
        giaVe: 170000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50059,
        tenGhe: 'I5-I6',
        loaiGhe: 'TWIN',
        stt: '99',
        giaVe: 170000,
        daDat: false,
        dangChon: false,
    },
    {
        maGhe: 50060,
        tenGhe: 'I7-I8',
        loaiGhe: 'TWIN',
        stt: '100',
        giaVe: 170000,
        daDat: false,
        dangChon: false,
    },
];
